In [16]:
# import libraries
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Ignore warnings
import warnings
warnings.filterwarnings("ignore")

# Display all columns
pd.set_option('display.max_columns', None)

In [17]:
df = pd.read_csv("WA_Fn-UseC_-HR-Employee-Attrition.csv")
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,Research Scientist,2,Married,5130,24907,1,Y,No,23,4,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,Laboratory Technician,3,Single,2090,2396,6,Y,Yes,15,3,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,Research Scientist,3,Married,2909,23159,1,Y,Yes,11,3,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,Laboratory Technician,2,Married,3468,16632,9,Y,No,12,3,4,80,1,6,3,3,2,2,2,2

In [18]:
df['OverallSatisfaction'] = ( df['EnvironmentSatisfaction'] + df['JobSatisfaction'] + df['RelationshipSatisfaction'] + df['WorkLifeBalance'] ) / 4
df['TenureRatio'] = ( df['YearsAtCompany'] / df['TotalWorkingYears'].replace(0, np.nan).fillna(0) )

In [19]:
df = df.drop(columns=[
    "EnvironmentSatisfaction","JobSatisfaction","RelationshipSatisfaction","WorkLifeBalance","YearsAtCompany","TotalWorkingYears",
    "Over18","EmployeeCount","EmployeeNumber","StandardHours","DailyRate","EducationField","MonthlyIncome","MonthlyRate","TrainingTimesLastYear"])

In [ ]:
df.head()

In [21]:
df['OverTime'] = df['OverTime'].map({ 'Yes':1, 'No':0 })
df['Attrition'] = df['Attrition'].map({ 'Yes':1, 'No':0 })
df['BusinessTravel'] = df['BusinessTravel'].map({ 'Travel_Frequently':2, 'Travel_Rarely':1, 'Non-Travel':0 })
df['Gender'] = df['Gender'].map({ 'Female':1, 'Male':0 })

In [22]:
df['Department'] = df['Department'].map({'Research & Development':2, 'Sales':1, 'Human Resources':0 })

In [23]:
df['JobRole'] = df['JobRole'].map({'Healthcare Representative': 0,'Human Resources': 1,'Laboratory Technician': 2,'Manager': 3,
'Manufacturing Director': 4,'Research Director': 5,'Research Scientist': 6,'Sales Executive': 7,'Sales Representative': 8})

In [24]:
df['MaritalStatus'] = df['MaritalStatus'].map({'Single': 0,'Married': 1,'Divorced': 2})

In [25]:
df.head()

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,MaritalStatus,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,StockOptionLevel,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,OverallSatisfaction,TenureRatio
0,41,1,1,1,1,2,1,94,3,2,7,0,8,1,11,3,0,4,0,5,2.00,0.750000
1,49,0,2,2,8,1,0,61,2,2,6,1,1,0,23,4,1,7,1,7,3.00,1.000000
2,37,1,1,2,2,2,0,92,2,1,2,0,6,1,15,3,0,0,0,0,3.00,0.000000
3,33,0,2,2,3,4,1,56,3,1,6,1,1,1,11,3,0,7,3,0,3.25,1.000000
4,27,0,1,2,2,1,0,40,3,1,2,1,9,0,12,3,1,2,2,2,2.50,0.333333

In [27]:
df.to_csv(r"E:\ironhack\IH_PROJECTS\ML_Project\df_FE.csv", index=False)

In [28]:
df["MaritalStatus"].value_counts()

MaritalStatus
1    673
0    470
2    327
Name: count, dtype: int64